name: "STAGING ENV: Snowflake Terraform Demo Workflow"

on:
  push:
    branches:
      - staging
  workflow_dispatch:
   

jobs:
  deploy-terraform-staging:
    name: "Plan & Deploy Terraform plan on Staging"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::103074025996:role/snowflake-demo-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Init
        id: init
        run: terraform -chdir=./staging init

      - name: Terraform Format
        id: fmt
        run: terraform -chdir=./staging fmt -recursive -check

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=./staging validate -no-color

      - name: Terraform Plan
        id: plan
        run: |
          export TF_VAR_snowflake_private_key="${{ secrets.SNOWFLAKE_PRIVATE_KEY }}"
          export TF_VAR_snowflake_user="cicduser"
          export TF_VAR_snowflake_account="xr96327"
          export TF_VAR_snowflake_role="SNOWFLAKE_LEARNING_ROLE"
          terrafirm  -chdir=./staging plan
      - name: Terraform Apply
        id: apply
        run: terraform -chdir=./staging apply -auto-approve